import Head from 'next/head' 
import Navbar from '../components/Navbar';
import HeroBox from '../components/Main/HeroBox';
import AboutUs from '../components/Main/AboutUs';
import UseML from '../components/Main/UseML';
import AIForEveryone from '../components/Main/AIForEveryone';
import RDAISolutions from '../components/Main/RDAISolutions';
export default function Home() {


  return (
    <div className="min-h-screen bg-black">
      <Head>
        <title>Stable Diffusion</title>
        <meta name="description" content="Generated by Stable Diffusion " />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <main className='text-white w-full flex flex-col justify-center items-center' >
        <HeroBox/>
        <AboutUs/>
        <UseML/>
        <AIForEveryone/>
        <RDAISolutions/> 
      </main>

    </div>

  )
}
