import Head from 'next/head' 
import Navbar from '../components/Navbar'; 
import HeroBoxProduct from '../components/ProductPage/HeroBoxProduct';
import PersonaProduct from '../components/ProductPage/PersonaProduct';
import AudioProduct from '../components/ProductPage/AudioProduct';
import ChatBotProduct from '../components/ProductPage/ChatBotProduct';
import CopyrightNotic from '../components/CopyrightNotic';
export default function Products() { 
  return (
    <div className="min-h-screen bg-white">
      <Head>
        <title>Stable Diffusion</title>
        <meta name="description" content="Generated by Stable Diffusion " />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <main className='text-white w-full flex flex-col justify-center items-center' >
        <HeroBoxProduct/>
        <PersonaProduct/>
        <AudioProduct/>
        <ChatBotProduct/>
      </main>
      <CopyrightNotic/> 
    </div>

  )
}
